# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

jobs:
  include:
    - r: release
      after_success:
        - R CMD INSTALL $PKG_TARBALL
        - Rscript -e 'lintr::lint_package()'
        - Rscript -e 'covr::codecov()'
      deploy:
        on:
          branch: master
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
    - r: oldrel
    - r: devel
