# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r:
  - oldrel
  - release
  - devel

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
