# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

jobs:
  include:
    - r: release
      after_success:
        - R CMD INSTALL $PKG_TARBALL
        - Rscript -e 'lintr::lint_package()'
        - Rscript -e 'covr::codecov()'
      deploy:
        if: branch = master
        skip_cleanup: true
        - Rscript -e 'pkgdown::deploy_site_github()'
    - r: oldrel
    - r: devel
